CS-Social-Good-CalPoly/Vera

- netlify.toml
Working on getting deployment for the site...
> Added netlify config file

- frontend/src/components/DropDownOptionalForm/DropDownOptionalForm.css
Changed the font color for the major selection from a faint gray to match all of the other text.
> Fixed Major Selection Font Color

- backend/routes/stories.js
- frontend/netlify.toml
Trying this solution provided from this StackOverFlow thread: https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router
> Addressing The Netlify Refresh "Page Not Found" Issue

- frontend/src/components/IndividualResourceTile/IndividualResourceTileCollapsed.js
- frontend/src/components/ResourcePageTile/ResourcePageTile.js
- frontend/src/components/Shared/TruncateText.jsx
- frontend/src/components/StoryPopUp/StoryPopUp.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/pages/StoriesPage/StoriesPage.js
added a couple .catch() but I'm not sure they're completely working yet
> adding some .catch() 

- frontend/package.json
- frontend/src/components/Navbar/Navbar.css
- frontend/src/components/Navbar/Navbar.js
Well. I tried to fix this in a more elegant way with css styling, but that didn't seem to have any effect. So this is honestly not the most elegant way to solve this problem, however. The functionality is perfect. I basically just added some states and some in line css styling.
> nav bar now underlines the current page

- frontend/src/components/Footer/Footer.js
I added an onClick to the Link component that includes some logic for redirecting the scroll to the top of the page.
> fixed scroll issue

- backend/routes/stories.js
Here I tested the delete endpoint, all that needs to be passed in the body is the id of the story to delete.
Here I tested the update endpoint by changing the title of an existing story. All that needs to be passed to the body is the id and the fields that should be updated of the story to update.
> Admin endpoints

- frontend/src/App.js
- frontend/src/components/Navbar/Navbar.css
- frontend/src/components/Navbar/Navbar.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/pages/StoriesPage/StoriesPage.js
- frontend/src/pages/StorySubmissionPage/StorySubmissionPage.js
Closes #257 
Added `const [activeLink, setActiveLink] = useState(null)` in `App.js`. This is passed to the `Navbar`, `HomePage`, `StoriesPage`, and `StorySubmissionPage` components to keep track of which page is currently "active". Then, using a `NavLink` element instead of a `Link` element in the `Navbar`, the `Navbar` dynamically adds an underline to the "active" page.
`HomePage`, `StoriesPage`, and `StorySubmissionPage` now have a `setActiveLink` prop which is then called in a `useEffect` once the page is rendered. Since `activeLink` is passed to the `Navbar`, this changes which text is underlined, even when the `Footer` links are clicked.
To apply this to future pages on the navbar, the following changes are needed:
1. In `App.js`, under the `Route` component, set the `component` …
> #257 - Adding Underline To NavBar When Clicking on Footer Links

- backend/models/Tokens.js
- backend/routes/stories.js
I created the `Tokens.js` file in `backend/models` which creates and exports the `TokenSchema`. The `TokenSchema` has 2 attributes: 1) Value (string, required) which is the actual token, and 2) AssociatedStories (Array of strings, required) which is a list of references to the stories associated with the specific token.
Then, in `backend/routes/stories.js`, I used the `/tokens` URL to create a `GET` endpoint which returns all the tokens from the MongoDB collection. To test this, I added a few token documents with dummy data.
> #247 - Story Token (part 2) Complete

- backend/routes/stories.js
- frontend/src/components/StorySubmission/StorySubmission.css
- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/links.js
Before, when the user selects a category, it didn't update on the database, but now the chosen category is added to the RelevantCategoryList, and the associated story  is added to the Category's StoryIDList with a PUT request. 
NOTE: the put request doesn't seem to work without "e.preventDefault() in the handlePost function (line 155) but this makes it so that the inputs don't clear after submission.
> Add selected Category to backend

- backend/package.json
- backend/routes/stories.js
- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/links.js
Vastly improved the speed of grabbing the majors via the web scraping by moving it to be its own endpoint (server-side) as opposed to where it originally was (frontend/client-side).
> Improve fetching speed of majors

- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/pages/AdminPage/AdminPages.js
In this issue, I added a button titled "Review" which toggles whether or not we are seeing all stories or the ones that are marked is "review" in the Status field. When the button is clicked, it will show only stories with "review" and when it Is clicked again, it will go back to showing everything.
> Add Admin Page Filtering

- backend/routes/stories.js
- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/components/StorySubmissionPopUp/StorySubmissionPopUp.css
- frontend/src/components/StorySubmissionPopUp/StorySubmissionPopUp.js
Closes #295 
Completed task. Created PUT request for tokens to allow existing tokens to append a new storyID to the `AssociatedStories` array. The popup now prompts the user to input their existing tokens or create a new one. If a new one is created, after clicking the submit button, both the story and token will be `POST`ed, with the storyID connected to the token's `AssociatedStories` array. If the user inputs an existing token and that token is in fact in the database, then the new story will be `POST`ed and it's storyID will be added to the inputted token's `AssociatedStories` array through a `PUT`
> 295 story tokens part 5

- frontend/src/components/Footer/Footer.js
Changed Footer.js to also include the "Share Your Story" button as it appears in the header. The added code the same structure (same classes, formatting) as the rest of the footer links.
> Added Share Your Story to Footer

- frontend/src/App.js
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
Now the footer has underlining for the section names similar to the navbar. The footer component now also takes in the activeLink state.
> added underlining in the footer

- frontend/src/App.js
- frontend/src/components/Navbar/Navbar.js
- frontend/src/pages/LandingPage/LandingPage.js
Closes #301 
Added Home tab to navbar
I am not sure if active link was set correctly, a bit confused of what active link does so just followed the format of other active link show there
> added home page to navbar

- backend/models/CollegeMajors.js
Created a new model for Colleges and Majors. This is for issues #336 and #337. The MongoDB collection has already been made
> Add CollegeMajors Schema

- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/pages/StoriesPage/StoriesPage.js
Removed the console logs mentioned in the issue.
> Removing console logs

- frontend/src/App.js
- frontend/src/components/ResourcePageTile/ResourcePageTile.js
- frontend/src/components/ResourcePageTileGroup/ResourcePageTileGroup.js
- frontend/src/components/ResourcePopUp/ResourcePopUp.js
- frontend/src/components/components.js
- frontend/src/pages/IndividualResourcePage/IndividualResourcePage.js
Closes #312 
* Created resource pop up page and passed in resource's MongoDB object id 
* Replaced getLocation call with a fetch for all stories in MongoDB since location's state does not save when sharing the url
> Add unique resource page url

- frontend/src/components/Banner/Banner.js
Closes #299 
Added a line of code that checks props.logo and renders logo conditionally
> conditionally renders logo depending on props.logo

- backend/routes/web_scraping.js
- Changed the title to be shortened: "The Pharmacy at Campus Health & Wellbeing | Campus Health & Wellbeing" to just The Pharmacy at Campus Health & Wellbeing. I can change it back too j thought it was kinda long, lmk!
- Phone number is the generic health services phone number on the info bar in the right. I think theres another number mentioned on the page but not sure if we want to include that one?
- Image didn't have alt attribute, so I just hardcoded one
> addded pharmacy scraping

- backend/app.js
- backend/routes/colleges_scraper.js
- frontend/src/pages/AdminPage/AdminPages.js
Closes #336 too
- Added file colleges_scraper
- Scraping Includes BS/MS but not minor or other programs 
- Instead of having a PUT request and then calling it, the scrapping logic is done inside the PUT request
1) sync_colleges: syncs all 6 colleges by calling college majors with a body that looks something like "college: OCOB". This is the route that the button in AdminPages calls. 
2) college_majors: give the college in the body to scrape the specific college. 
- Goes to 'https://catalog.calpoly.edu/collegesanddepartments/' and scrapes the collegeurls
- Navigates to the corresponding url and scrapes the table info, filtering for BS/MS majors
> 337 web scraper colleges and majors part 2

- backend/routes/web_scraping.js
Closes #356
Scraped all field in individual resources schema from Emotional Wellbeing Workshop website
Wasn't able to check if the emotional wellbeing resource was inside dev resources in the website as instructions to do so were unclear
Postman Result
Checking if added to MongoDB
> Implemented Emotional Wellbeing Scraping Route

- backend/routes/stories.js
- frontend/src/pages/StoriesPage/StoriesPage.js
* Add: backend route that GETs all stories associated with a specific token, frontend function that calls this route (not attached to any UI yet)
> #348 GET Request for Stories Associated with a Specific Token

- frontend/src/components/DropDownSelectForm/DropDownSelectForm.js
- frontend/src/components/StorySubmission/StorySubmission.js
- frontend/src/components/components.js
- frontend/src/pages/AdminPage/AdminPages.css
- frontend/src/pages/AdminPage/AdminPages.js
- frontend/src/pages/StoriesPage/StoriesPage.js
- new component uses the react-select component
- I believe all of the site uses this new component instead of DropDownForm and DropDownOptionalForm (kept them in just in case)
- I'm not sure the reason for the optional form, not sure how the optional part is taken care of so might have to update the component to handle optional dropdowns?
- It might be a good idea to remove the other dropdown components if everything looks good
- can add a custom style to the component to help with more flexibility in styling 
- Looks good overall I think. We can probably edit the default styles to add some more styles like color and padding depending on what we think
> added dropdown select form + changed all dropdowns

- backend/routes/stories.js
- Tries to grab a token, returns 400 message if not there
- Tries to see if the story is in associated stories, 400 error if not
- follows the same logic from admin updateput request
> added updateStory with token route

- frontend/src/components/DropDownForm/DropDownForm.js
- frontend/src/components/DropDownOptionalForm/DropDownOptionalForm.js
- frontend/src/components/EditStory/EditStory.js
Closes #350 
Implemented Edit Story Pop Up and changed DropDowns to take in props to dynamically set dropdown fields in edit story pop up
> Implemented Edit Story Pop Up

- backend/routes/web_scraping.js
Issue:  #380 
Web scrapes:   https://chw.calpoly.edu/counseling/apps
I finished the script, but haven't tested it yet so don't merge.
> Web Scraping Welltrack Boost

- backend/routes/stories.js
- frontend/src/components/DropDownSelectForm/DropDownSelectForm.js
- frontend/src/components/StorySubmission/StorySubmission.js
#377 
Connects backend to frontend. Backend `GET` requests for colleges and majors are now used to populate the "College" and "Major" dropdowns.
Also, fixed an issue with posting new stories.
> Fix college and majors

- backend/routes/web_scraping.js
#381 
Implemented web scraper for Cal Poly's Suicide Prevention page. Verified with Postman, and the resource is viewable on the page now.
> Suicide prevention scraper

- frontend/src/pages/ResourcePage/ResourcePage.css
- frontend/src/pages/ResourcePage/ResourcePage.js
- frontend/src/pages/StoriesPage/StoriesPage.css
- frontend/src/pages/StoriesPage/StoriesPage.js
Attempts to close #390
- Search bar is sticky (made it sticky for the stories too)
- Clear button to clear out the dropdown menu filter
- You can search in (3) ways
1) Use the dropdown: Will scroll to the section
2) Use the search features: Will scroll to the category section on enter
3) Use both: (Should) scroll to section and then filter through what you have
* for using both it might be useful to just have it sort instead of filter out all the results?
* Play around with it and lmk what you think!
> added searchbar to research page

- backend/routes/web_scraping.js
- frontend/src/pages/ResourcePage/ResourcePage.js
Closes #334 
Finished @ewong128 web scraper for Cal Poly's [Eating Disorder Treatment](https://chw.calpoly.edu/counseling/eating-disorder-treatment) page. Added to the database via Postman. Also, fixed some category mapping in the Resource page to properly display resources.
Note: I set the category to "Counseling and Psychological Services" as it seemed more appropriate than "Food Resources", but this can easily be changed by modifying the `Category` field in the new `IndResource`.
> Eating disorder

- backend/routes/web_scraping.js
#419 
Web Scrapes the general Let's Talk resource.
Link: https://chw.calpoly.edu/counseling/lets-talk
> Web Scraper for Let's Talk

- backend/routes/web_scraping.js
Issue: #415 
For Financial Resources and Education
> [Web Scraper] Cal Poly Grants

- frontend/src/components/StoryPopUp/StoryPopUp.js
- frontend/src/components/StoryTile/StoryTile.js
- frontend/src/components/StoryTileGroup/StoryTileGroup.js
- frontend/src/pages/IndividualStoryPage/IndividualStoryPage.js
- frontend/src/pages/StoriesPage/StoriesPage.css
- frontend/src/pages/StoriesPage/StoriesPage.js
closes #347 
We should be able to:
1. use the token input to create a section called "Your Stories"
2. when clicking on the story, if we inputted a token then it should be editable
3. We can search through both sections using the search bar
4. instead of filtering we sort the stories
> 347 add text input for tokens in stories page

- backend/routes/web_scraping.js
- frontend/src/components/Footer/Footer.css
- frontend/src/components/Footer/Footer.js
- frontend/src/components/IndividualResourceTile/IndividualResourceTileExpanded.css
- frontend/src/components/IndividualResourceTile/IndividualResourceTileExpanded.jsx
You can now quickly go to a new page in the resources page if a resource's extra info has a url in it.
> Converting Strings into URL Links

- backend/app.js
- backend/routes/tags.js
- frontend/src/components/ResourceTag/ResourceTag.js
- frontend/src/links.js
- frontend/src/pages/AdminPage/AdminPages.css
- frontend/src/pages/AdminPage/AdminResourcesPage.js
#413 and #407 
Implemented tagging system for resources, enabling admin to add, delete, and manage tags both on the backend and frontend. 
* **New API Endpoints for Tag Management**:
- Added a new `tags.js` route file with methods to add (`POST /tags/add`) and remove (`DELETE /tags/remove/:resourceId/:tag`) tags for resources. These validate input, prevent duplicate tags, and update the database accordingly.
* **Tag Management in Admin Resources Page**:
- Updated `AdminResourcesPage.js` to allow admins to add and delete tags for resources. This includes:
- A predefined list of tags for quick selection.
- Input fields and dropdowns for adding new or predefined tags.
- Error handling for duplicate tags.
- Integration with the backend API for tag add/delete operations.
* **Environment …
> AdminResource Tagging Frontend and Backend

- frontend/src/components/CategoryButton/CategoryButton.css
- frontend/src/components/CategoryButtonGroup/CategoryButtonGroup.css
- frontend/src/components/DropDownForm/DropDownForm.css
- frontend/src/components/DropDownOptionalForm/DropDownOptionalForm.css
- frontend/src/components/DropDownSelectForm/DropDownSelectForm.js
- frontend/src/components/IndividualResourceTile/IndividualResourceTileExpanded.css
- frontend/src/components/IndividualResourceTile/IndividualResourceTileExpanded.jsx
- frontend/src/components/LinkButton/LinkButton.css
- frontend/src/components/Shared/Fonts/PageTitle.js
- frontend/src/components/Shared/Tile.js
- frontend/src/components/Shared/TileGroup.js
- frontend/src/components/StoryBanner/storyBanner.css
- frontend/src/components/StoryPopUp/StoryPopUp.js
- frontend/src/components/StorySubmission/StorySubmission.css
- frontend/src/components/StorySubmissionPopUp/StorySubmissionPopUp.css
- frontend/src/components/StoryTile/StoryTile.js
- frontend/src/pages/AdminPage/AdminPages.css
- frontend/src/pages/ResourcePage/ResourcePage.css
- frontend/src/pages/StoriesPage/StoriesPage.css
Changed all "uppercase" CSS to "capitalize" so that it doesn't look like the screen is shouting at you. 
Also added url linking to location/address so that if it's a Zoom link, it can easily be clicked on.
> UI Changes for a Cleaner Look

- backend/routes/web_scraping.js
Closes #434 
Implemented web scraper for Off Campus Housing support.
> Web Scraping Off Campus Housing

- backend/routes/web_scraping.js
Closes #424
Implements the web scraper for the Community Referral resource. Note, that we're renaming the title as "Find a Therapist" so it's more obvious what this resource provides. This means the title is hard coded and there's a slight discrepancy between the title and the image, but that's not a huge deal.
> Find a Therapist Web Scraper

- backend/routes/stories.js
- frontend/src/components/EditStory/EditStory.js
- frontend/src/components/StoryPopUp/StoryPopUp.css
- frontend/src/components/StoryPopUp/StoryPopUp.js
- frontend/src/pages/IndividualStoryPage/IndividualStoryPage.js
closes #384 
Functionality for updating and deleting a story works 
(also made the edit popup z-value high so the footer isn't a problem lol)
- delete function now also deletes from the token db ( I forgot to this before so there are some dead links under token 0123456789abcdef i.e. they refer to a story that doesn't exist )
- I think the delete works now from both stories and tokens table
> added update and delete functionality to edit stories

- backend/routes/resources.js
- backend/routes/tags.js
- frontend/src/pages/ResourcePage/ResourcePage.js
- frontend/src/pages/StoriesPage/StoriesPage.js
Remove Weird Page Headers
[#393](https://github.com/CS-Social-Good-CalPoly/Vera/issues/393)
Followed the notes in the issue linked above.  Just deleted the code for the banner to appear in the page. Did not delete the code to make the banner and the pages that were edited is the resource and stories page in the frontend. Also, ran npm run format, to clear up any code format issues.
> Deleted Banners and ran formatter

- backend/routes/web_scraping.js
Adds the web scraper for [Cal Poly's Safer](https://safer.calpoly.edu/). Since there's a LOT of important information on the site, I only scraped the headers of each section for the `ExtraInfo` field with a note saying to read more at the actual website.
Since resource `Tags` are supposed to represent keywords to aid our fuzzy searching, I included the following tags. Most of them are not tags within our database, but can be easily added.
- Counseling
- Therapy
- Mental Health
- Sexual Assault
- Abuse
- Violence
- Harassment
Also, not sure what category to put it under, so I used "Health Services" but this can easily be changed.
> finish safer web scraper

- backend/routes/web_scraping.js
Resolved Issue #449 
Simple web scraper that grabs some info from https://chw.calpoly.edu/m4r
The extra info contains the meetings information seeing how it varies each quarter and has different locations/times for each one.
> Mustangs for Recovery Web Scraper
